[general]
context=from-internal
allowoverlap=no
clearglobalvars=no

[from-internal]
exten => 1000,1,Answer()
exten => 1000,n,VoiceMail(1000@default)
exten => 1000,n,Hangup()

exten => 2000,1,Answer()
exten => 2000,n,Playback(demo-congrats)
exten => 2000,n,Hangup()

exten => 3000,1,Answer()
exten => 3000,n,AGI(agi://localhost:4573)
exten => 3000,n,Hangup()

exten => _.,1,Goto(${EXTEN},1)
