[general]
state=up

[default]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw,alaw,gsm
auth=auth-default
aor=aor-default

[auth-default]
type=auth
auth_type=userpass
password=password
username=admin

[aor-default]
type=aor
max_contacts=1
contact=sip:localhost
