[general]
port = 5060
protocol = udp
bind_addr = 0.0.0.0
allow = ulaw
allow = alaw
allow = gsm
disallow = all

[peer-default](!!!)
type=peer
disallow=all
allow=ulaw
allow=alaw
allow=gsm
host=dynamic
nat=yes

[user-default](!!!)
type=user
context=from-internal
